/** The one immutable cross-device benchmark selected by the first recording. */
export interface HumanStrokeBenchmarkRecord {
  id: "canonical";
  payloadJson: string;
  capturedAt: string;
}

export const humanStrokeBenchmarkSchemaSql = `
CREATE TABLE IF NOT EXISTS human_stroke_benchmark (
  id TEXT PRIMARY KEY NOT NULL CHECK (id = 'canonical'),
  payload_json TEXT NOT NULL,
  captured_at TEXT NOT NULL
)
`;

/** Append-only performance measurements generated by each replay. */
export interface BenchmarkRunRecord {
  id: number;
  createdAt: string;
  payloadJson: string;
}

export const benchmarkRunsSchemaSql = `
CREATE TABLE IF NOT EXISTS benchmark_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL,
  payload_json TEXT NOT NULL
)
`;

/** Append-only lossless-compression measurements for inactive layer tiles. */
export interface LayerCompressionRunRecord {
  id: number;
  createdAt: string;
  payloadJson: string;
}

export const layerCompressionRunsSchemaSql = `
CREATE TABLE IF NOT EXISTS layer_compression_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL,
  payload_json TEXT NOT NULL
)
`;

/** One diagnostic C zoom-out report, addressed by the short code in its URL. */
export interface VectorZoomRunRecord {
  runCode: string;
  createdAt: string;
  payloadJson: string;
}

export const vectorZoomRunsSchemaSql = `
CREATE TABLE IF NOT EXISTS vector_zoom_runs (
  run_code TEXT PRIMARY KEY NOT NULL,
  created_at TEXT NOT NULL,
  payload_json TEXT NOT NULL
)
`;
