import type { HistoryAction, HistoryRenderBatch } from "./engine-history-types";

export const HISTORY_ACTION_KINDS = [
  "stroke",
  "fill",
  "clear",
  "vector",
  "document-background",
  "layer-blend-mode",
  "layer-metadata",
  "scene-reorder",
  "vector-rasterize",
  "raster-import",
  "raster-transform",
  "group-transform",
  "raster-filter",
  "layer-add",
  "layer-delete",
  "layer-merge",
] as const satisfies readonly HistoryAction["kind"][];

type MissingActionKind = Exclude<
  HistoryAction["kind"],
  (typeof HISTORY_ACTION_KINDS)[number]
>;
const ALL_ACTION_KINDS_ARE_LISTED: MissingActionKind extends never ? true : never = true;
void ALL_ACTION_KINDS_ARE_LISTED;

export const HISTORY_BATCH_KINDS = ["paint", "blend", "fill"] as const satisfies readonly
  HistoryRenderBatch["kind"][];
type MissingBatchKind = Exclude<
  HistoryRenderBatch["kind"],
  (typeof HISTORY_BATCH_KINDS)[number]
>;
const ALL_BATCH_KINDS_ARE_LISTED: MissingBatchKind extends never ? true : never = true;
void ALL_BATCH_KINDS_ARE_LISTED;

export type HistoryCharacterizationFamily =
  | "paint-blend"
  | "raster-operations"
  | "layer-properties-effects"
  | "layer-structure"
  | "selection"
  | "semantic-scene";

export interface HistoryActionCharacterization {
  readonly id: string;
  readonly family: HistoryCharacterizationFamily;
  readonly status: "current" | "legacy-compat";
  readonly owner: string;
  readonly currentMethods: readonly string[];
  readonly actionKinds: readonly HistoryAction["kind"][];
  readonly batchKinds: readonly HistoryRenderBatch["kind"][];
  readonly lifecycle: "gesture" | "session" | "atomic" | "structural-transaction";
  readonly commitPolicy:
    | "first-accepted-geometry"
    | "post-gpu-operation"
    | "post-cpu-operation"
    | "gesture-end"
    | "session-apply"
    | "post-structural-apply"
    | "owned-by-parent-action"
    | "legacy-read-only";
  readonly cancelPolicy:
    | "pre-submit"
    | "restore-session-snapshot"
    | "untouched-only"
    | "not-applicable"
    | "owned-by-parent-action"
    | "legacy-only";
  readonly branchCut: "on-commit" | "owned-by-parent-action" | "none-legacy";
  readonly payload:
    | "gpu-stamp-batch"
    | "gpu-blend-batch"
    | "gpu-fill-mask"
    | "replay-barrier"
    | "cpu-delta"
    | "cold-seed"
    | "conditional-cold-seed"
    | "mixed"
    | "selection-mask-snapshot"
    | "none";
  readonly payloadOwner:
    | "history-gpu-storage"
    | "history-action"
    | "history-journal"
    | "parent-action"
    | "legacy-vector-action";
  readonly release: "redo-compaction" | "journal-only" | "parent-action" | "legacy-compat";
  readonly replay:
    | "batch-rebuild"
    | "checkpoint-hydration"
    | "metadata-swap"
    | "structural-swap"
    | "parent-action";
  readonly undoRedoPath: string;
  readonly spillable: boolean;
  readonly selection:
    | "none"
    | "coupled-snapshot"
    | "baked-into-payload"
    | "before-after"
    | "not-independent";
  readonly faultBoundary: "cpu" | "gpu-cpu" | "structural-gpu";
  readonly currentAtomicity: "verified" | "known-gap";
  readonly currentRisk: string | null;
  readonly recovery: string;
  readonly verifiers: readonly string[];
}

/**
 * Living map of every mutation that can reach the global History journal.
 * Pixel selection deliberately has no parallel action kind: its state is
 * owned by Paint or selection Transform, while Fill bakes clipping into its
 * authoritative 1-bit payload.
 */
export const HISTORY_ACTION_CHARACTERIZATION = [
  {
    id: "paint",
    family: "paint-blend",
    status: "current",
    owner: "BrushEngine stroke gesture -> History transaction",
    currentMethods: ["beginStrokeAtLayer", "recordHistoryBatch", "endStroke"],
    actionKinds: ["stroke"],
    batchKinds: ["paint"],
    lifecycle: "gesture",
    commitPolicy: "first-accepted-geometry",
    cancelPolicy: "pre-submit",
    branchCut: "on-commit",
    payload: "gpu-stamp-batch",
    payloadOwner: "history-gpu-storage",
    release: "redo-compaction",
    replay: "batch-rebuild",
    undoRedoPath: "moveHistoryCursor -> rebuildActiveLayerFromHistory -> submitImmediate",
    spillable: true,
    selection: "coupled-snapshot",
    faultBoundary: "gpu-cpu",
    currentAtomicity: "known-gap",
    currentRisk: "the first GPU submit precedes CPU publication; a rejected commit releases the payload and latches the document instead of replaying inside the frame callback",
    recovery: "release the unpublished payload exactly once and enter the engine-wide inconsistent-state gate",
    verifiers: ["verify-history-journal.mjs", "verify-layer-stack.mjs"],
  },
  {
    id: "blend",
    family: "paint-blend",
    status: "current",
    owner: "BrushEngine blend gesture -> History transaction",
    currentMethods: ["beginStrokeAtLayer", "recordBlendHistoryBatch", "endStroke"],
    actionKinds: ["stroke"],
    batchKinds: ["blend"],
    lifecycle: "gesture",
    commitPolicy: "first-accepted-geometry",
    cancelPolicy: "pre-submit",
    branchCut: "on-commit",
    payload: "gpu-blend-batch",
    payloadOwner: "history-gpu-storage",
    release: "redo-compaction",
    replay: "batch-rebuild",
    undoRedoPath: "moveHistoryCursor -> rebuildActiveLayerFromHistory -> submitBlendImmediate",
    spillable: true,
    selection: "none",
    faultBoundary: "gpu-cpu",
    currentAtomicity: "known-gap",
    currentRisk: "the first GPU submit precedes CPU publication; a rejected commit releases the payload and latches the document instead of replaying inside the frame callback",
    recovery: "release the unpublished payload exactly once and enter the engine-wide inconsistent-state gate",
    verifiers: ["verify-history-journal.mjs", "verify-blend-core.mjs"],
  },
  {
    id: "fill",
    family: "raster-operations",
    status: "current",
    owner: "engine-fill-runtime",
    currentMethods: ["fillAtClientPoint", "submitFillHistoryBatch"],
    actionKinds: ["fill"],
    batchKinds: ["fill"],
    lifecycle: "atomic",
    commitPolicy: "post-gpu-operation",
    cancelPolicy: "not-applicable",
    branchCut: "on-commit",
    payload: "gpu-fill-mask",
    payloadOwner: "history-gpu-storage",
    release: "redo-compaction",
    replay: "batch-rebuild",
    undoRedoPath: "moveHistoryCursor -> rebuildActiveLayerFromHistory -> submitFillHistoryBatch",
    spillable: true,
    selection: "baked-into-payload",
    faultBoundary: "gpu-cpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "release mask and rebuild the active layer from the pre-operation cursor",
    verifiers: ["verify-fill.mjs", "verify-layer-stack.mjs"],
  },
  {
    id: "clear",
    family: "raster-operations",
    status: "current",
    owner: "BrushEngine.clear",
    currentMethods: ["clear"],
    actionKinds: ["clear"],
    batchKinds: [],
    lifecycle: "atomic",
    commitPolicy: "post-gpu-operation",
    cancelPolicy: "not-applicable",
    branchCut: "on-commit",
    payload: "replay-barrier",
    payloadOwner: "history-journal",
    release: "journal-only",
    replay: "batch-rebuild",
    undoRedoPath: "moveHistoryCursor -> rebuildActiveLayerFromHistory using the per-layer clear barrier",
    spillable: false,
    selection: "none",
    faultBoundary: "gpu-cpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "rebuild the cleared layer if journal publication fails after the GPU clear",
    verifiers: ["verify-history-journal.mjs", "verify-layer-stack.mjs"],
  },
  {
    id: "destructive-raster-filters",
    family: "raster-operations",
    status: "current",
    owner: "filter-specific runtime session",
    currentMethods: [
      "beginRasterGaussianBlur",
      "updateRasterGaussianBlur",
      "commitRasterGaussianBlur",
      "cancelRasterGaussianBlur",
      "beginRasterMotionBlur",
      "updateRasterMotionBlur",
      "commitRasterMotionBlur",
      "cancelRasterMotionBlur",
      "beginRasterNoise",
      "updateRasterNoise",
      "commitRasterNoise",
      "cancelRasterNoise",
      "beginRasterGlass",
      "updateRasterGlass",
      "reseedRasterGlass",
      "commitRasterGlass",
      "cancelRasterGlass",
      "beginRasterLiquify",
      "updateRasterLiquifySettings",
      "commitRasterLiquify",
      "cancelRasterLiquify",
    ],
    actionKinds: ["raster-filter"],
    batchKinds: [],
    lifecycle: "session",
    commitPolicy: "session-apply",
    cancelPolicy: "restore-session-snapshot",
    branchCut: "on-commit",
    payload: "cold-seed",
    payloadOwner: "history-action",
    release: "redo-compaction",
    replay: "checkpoint-hydration",
    undoRedoPath: "moveHistoryCursor -> rebuildActiveLayerFromHistory -> hydrate action seed",
    spillable: true,
    selection: "none",
    faultBoundary: "gpu-cpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "destroy unpublished seed and restore the session baseline",
    verifiers: [
      "verify-gaussian-blur.mjs",
      "verify-motion-blur.mjs",
      "verify-noise.mjs",
      "verify-glass.mjs",
      "verify-liquify.mjs",
    ],
  },
  {
    id: "layer-rasterize",
    family: "raster-operations",
    status: "current",
    owner: "engine-rasterize-layer-runtime",
    currentMethods: ["rasterizeActiveRasterLayer"],
    actionKinds: ["raster-filter"],
    batchKinds: [],
    lifecycle: "atomic",
    commitPolicy: "post-gpu-operation",
    cancelPolicy: "not-applicable",
    branchCut: "on-commit",
    payload: "cold-seed",
    payloadOwner: "history-action",
    release: "redo-compaction",
    replay: "checkpoint-hydration",
    undoRedoPath:
      "moveHistoryCursor -> restore effect/source metadata -> rebuildActiveLayerFromHistory",
    spillable: true,
    selection: "none",
    faultBoundary: "gpu-cpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery:
      "destroy the unpublished seed, restore source/effects, and replay the pre-rasterize cursor",
    verifiers: ["verify-layer-rasterize.mjs"],
  },
  {
    id: "raster-transform",
    family: "raster-operations",
    status: "current",
    owner: "engine-raster-transform-runtime session",
    currentMethods: [
      "beginRasterLayerTransform",
      "updateRasterLayerTransform",
      "commitRasterLayerTransform",
      "cancelRasterLayerTransform",
    ],
    actionKinds: ["raster-transform"],
    batchKinds: [],
    lifecycle: "session",
    commitPolicy: "session-apply",
    cancelPolicy: "restore-session-snapshot",
    branchCut: "on-commit",
    payload: "mixed",
    payloadOwner: "history-action",
    release: "redo-compaction",
    replay: "checkpoint-hydration",
    undoRedoPath: "moveHistoryCursor -> rebuildActiveLayerFromHistory -> hydrate action seed and selection",
    spillable: true,
    selection: "before-after",
    faultBoundary: "gpu-cpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "destroy unpublished seed and restore raster plus selection snapshots",
    verifiers: ["verify-raster-transform.mjs", "verify-layer-stack.mjs"],
  },
  {
    id: "group-transform",
    family: "semantic-scene",
    status: "current",
    owner: "mixed-scene group Transform transaction",
    currentMethods: ["commitMixedSceneGroupTransform"],
    actionKinds: ["group-transform"],
    batchKinds: [],
    lifecycle: "session",
    commitPolicy: "session-apply",
    cancelPolicy: "restore-session-snapshot",
    branchCut: "on-commit",
    payload: "mixed",
    payloadOwner: "history-action",
    release: "redo-compaction",
    replay: "checkpoint-hydration",
    undoRedoPath:
      "moveHistoryCursor -> applyMixedSceneGroupTransformHistory -> replay every raster and semantic delta",
    spillable: true,
    selection: "none",
    faultBoundary: "structural-gpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "restore every member at the previous cursor before releasing the original active layer",
    verifiers: ["verify-group-transform-history.mjs"],
  },
  {
    id: "layer-blend-mode",
    family: "layer-properties-effects",
    status: "current",
    owner: "BrushEngine layer presentation",
    currentMethods: ["setLayerBlendMode"],
    actionKinds: ["layer-blend-mode"],
    batchKinds: [],
    lifecycle: "atomic",
    commitPolicy: "post-gpu-operation",
    cancelPolicy: "not-applicable",
    branchCut: "on-commit",
    payload: "cpu-delta",
    payloadOwner: "history-journal",
    release: "journal-only",
    replay: "metadata-swap",
    undoRedoPath: "moveHistoryCursor -> apply layer blend mode before/after",
    spillable: false,
    selection: "none",
    faultBoundary: "gpu-cpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "restore the previous presentation value if publication fails",
    verifiers: ["verify-layer-blend-modes.mjs"],
  },
  {
    id: "layer-metadata-effects",
    family: "layer-properties-effects",
    status: "current",
    owner: "raster metadata gesture",
    currentMethods: [
      "beginRasterLayerMetadataHistoryEdit",
      "commitRasterLayerMetadataHistoryEdit",
      "cancelRasterLayerMetadataHistoryEdit",
    ],
    actionKinds: ["layer-metadata"],
    batchKinds: [],
    lifecycle: "gesture",
    commitPolicy: "gesture-end",
    cancelPolicy: "untouched-only",
    branchCut: "on-commit",
    payload: "cpu-delta",
    payloadOwner: "history-journal",
    release: "journal-only",
    replay: "metadata-swap",
    undoRedoPath: "moveHistoryCursor -> assignRasterLayerMetadataHistoryValue",
    spillable: false,
    selection: "none",
    faultBoundary: "gpu-cpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "restore the before value and latch if its derived presentation cannot be rebuilt synchronously",
    verifiers: ["verify-mobile-raster-effects-sheet.mjs", "verify-layer-stack.mjs"],
  },
  {
    id: "document-background",
    family: "layer-properties-effects",
    status: "current",
    owner: "BrushEngine document backdrop",
    currentMethods: [
      "setDocumentBackgroundVisibility",
      "setDocumentBackgroundColor",
    ],
    actionKinds: ["document-background"],
    batchKinds: [],
    lifecycle: "atomic",
    commitPolicy: "post-cpu-operation",
    cancelPolicy: "not-applicable",
    branchCut: "on-commit",
    payload: "cpu-delta",
    payloadOwner: "history-journal",
    release: "journal-only",
    replay: "metadata-swap",
    undoRedoPath: "moveHistoryCursor -> applyDocumentBackgroundHistoryState",
    spillable: false,
    selection: "none",
    faultBoundary: "cpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "apply the immutable before/after document background state",
    verifiers: ["verify-history-journal.mjs", "verify-layer-panel-controller.mjs"],
  },
  {
    id: "layer-add",
    family: "layer-structure",
    status: "current",
    owner: "BrushEngine.addLayer",
    currentMethods: ["addLayer", "addClippingMaskLayer"],
    actionKinds: ["layer-add"],
    batchKinds: [],
    lifecycle: "structural-transaction",
    commitPolicy: "post-structural-apply",
    cancelPolicy: "not-applicable",
    branchCut: "on-commit",
    payload: "none",
    payloadOwner: "history-action",
    release: "redo-compaction",
    replay: "structural-swap",
    undoRedoPath: "moveHistoryCursor -> applyLayerAddHistory with an empty checkpoint",
    spillable: false,
    selection: "none",
    faultBoundary: "structural-gpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "remove the unpublished layer and restore selection/order; post-commit observers may only latch",
    verifiers: ["verify-layer-structure.mjs"],
  },
  {
    id: "layer-duplicate",
    family: "layer-structure",
    status: "current",
    owner: "BrushEngine.duplicateSelectedLayer",
    currentMethods: ["duplicateSelectedLayer"],
    actionKinds: ["layer-add"],
    batchKinds: [],
    lifecycle: "structural-transaction",
    commitPolicy: "post-structural-apply",
    cancelPolicy: "not-applicable",
    branchCut: "on-commit",
    payload: "conditional-cold-seed",
    payloadOwner: "history-action",
    release: "redo-compaction",
    replay: "structural-swap",
    undoRedoPath: "moveHistoryCursor -> applyLayerAddHistory with the duplicate baseline seed",
    spillable: true,
    selection: "none",
    faultBoundary: "structural-gpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "destroy the candidate seed and remove the unpublished duplicate",
    verifiers: ["verify-layer-duplicate.mjs", "verify-layer-stack.mjs"],
  },
  {
    id: "layer-delete",
    family: "layer-structure",
    status: "current",
    owner: "BrushEngine.deleteLayer",
    currentMethods: ["deleteLayer"],
    actionKinds: ["layer-delete"],
    batchKinds: [],
    lifecycle: "structural-transaction",
    commitPolicy: "post-structural-apply",
    cancelPolicy: "not-applicable",
    branchCut: "on-commit",
    payload: "mixed",
    payloadOwner: "history-action",
    release: "redo-compaction",
    replay: "structural-swap",
    undoRedoPath: "moveHistoryCursor -> applyLayerDeleteHistory",
    spillable: true,
    selection: "none",
    faultBoundary: "structural-gpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "destroy every partially captured seed or restore the complete deleted unit",
    verifiers: ["verify-layer-structure.mjs", "verify-layer-stack.mjs"],
  },
  {
    id: "scene-reorder",
    family: "layer-structure",
    status: "current",
    owner: "engine-history-runtime mixed-scene transaction",
    currentMethods: ["moveMixedSceneItem"],
    actionKinds: ["scene-reorder"],
    batchKinds: [],
    lifecycle: "structural-transaction",
    commitPolicy: "post-structural-apply",
    cancelPolicy: "not-applicable",
    branchCut: "on-commit",
    payload: "cpu-delta",
    payloadOwner: "history-journal",
    release: "journal-only",
    replay: "structural-swap",
    undoRedoPath: "moveHistoryCursor -> applyMixedSceneOrderState",
    spillable: false,
    selection: "none",
    faultBoundary: "structural-gpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "restore the captured scene order and rebuild presentation",
    verifiers: ["verify-mixed-scene-reorder.mjs"],
  },
  {
    id: "layer-merge",
    family: "layer-structure",
    status: "current",
    owner: "engine-layer-merge-runtime",
    currentMethods: ["mergeMixedSceneItems"],
    actionKinds: ["layer-merge"],
    batchKinds: [],
    lifecycle: "structural-transaction",
    commitPolicy: "post-structural-apply",
    cancelPolicy: "not-applicable",
    branchCut: "on-commit",
    payload: "mixed",
    payloadOwner: "history-action",
    release: "redo-compaction",
    replay: "structural-swap",
    undoRedoPath: "moveHistoryCursor -> applyLayerMergeHistory",
    spillable: true,
    selection: "none",
    faultBoundary: "structural-gpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "destroy output/input candidates or restore the complete source interval",
    verifiers: ["verify-layer-merge.mjs", "verify-layer-merge-vector-runs.mjs"],
  },
  {
    id: "pixel-selection",
    family: "selection",
    status: "current",
    owner: "parent Paint or raster-transform transaction",
    currentMethods: ["capturePaintSelectionHistoryMask", "commitRasterLayerTransform"],
    actionKinds: ["stroke", "raster-transform"],
    batchKinds: ["paint"],
    lifecycle: "session",
    commitPolicy: "owned-by-parent-action",
    cancelPolicy: "owned-by-parent-action",
    branchCut: "owned-by-parent-action",
    payload: "selection-mask-snapshot",
    payloadOwner: "parent-action",
    release: "parent-action",
    replay: "parent-action",
    undoRedoPath: "Paint clips replay with its snapshot; Transform restores before/after selection",
    spillable: true,
    selection: "not-independent",
    faultBoundary: "gpu-cpu",
    currentAtomicity: "known-gap",
    currentRisk: "Paint selection inherits the post-submit safe-latch boundary of its parent stroke",
    recovery: "the parent action releases or restores the selection payload",
    verifiers: ["verify-selection.mjs", "verify-pixel-selection-controller.mjs"],
  },
  {
    id: "text-svg-atomic",
    family: "semantic-scene",
    status: "current",
    owner: "BrushEngine semantic scene mutation",
    currentMethods: [
      "addVectorTextNode",
      "updateVectorTextNode",
      "setVectorTextNodeVisibility",
      "setVectorTextNodeOpacity",
      "moveVectorTextNode",
      "deleteVectorTextNode",
      "addVectorSvgNode",
      "updateVectorSvgNode",
      "setVectorSvgNodeVisibility",
      "setVectorSvgNodeOpacity",
      "moveVectorSvgNode",
      "deleteVectorSvgNode",
    ],
    actionKinds: ["vector"],
    batchKinds: [],
    lifecycle: "atomic",
    commitPolicy: "post-gpu-operation",
    cancelPolicy: "not-applicable",
    branchCut: "on-commit",
    payload: "cpu-delta",
    payloadOwner: "history-journal",
    release: "journal-only",
    replay: "metadata-swap",
    undoRedoPath: "moveHistoryCursor -> applyVectorHistoryState",
    spillable: false,
    selection: "none",
    faultBoundary: "structural-gpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "restore the semantic before snapshot and latch until presentation is safely rebuilt",
    verifiers: ["verify-vector-text.mjs"],
  },
  {
    id: "text-svg-gesture",
    family: "semantic-scene",
    status: "current",
    owner: "mixed-scene controller vector gesture",
    currentMethods: ["beginVectorHistoryEdit", "commitVectorHistoryEdit", "cancelVectorHistoryEdit"],
    actionKinds: ["vector"],
    batchKinds: [],
    lifecycle: "gesture",
    commitPolicy: "gesture-end",
    cancelPolicy: "restore-session-snapshot",
    branchCut: "on-commit",
    payload: "cpu-delta",
    payloadOwner: "history-journal",
    release: "journal-only",
    replay: "metadata-swap",
    undoRedoPath: "moveHistoryCursor -> applyVectorHistoryState",
    spillable: false,
    selection: "none",
    faultBoundary: "structural-gpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "keep the edit snapshot until publication succeeds; restore it and latch on rejection",
    verifiers: ["verify-vector-text.mjs"],
  },
  {
    id: "legacy-image-compat",
    family: "semantic-scene",
    status: "legacy-compat",
    owner: "project/history compatibility reader",
    currentMethods: ["restoreProjectDocument", "applyVectorHistoryState"],
    actionKinds: ["vector"],
    batchKinds: [],
    lifecycle: "atomic",
    commitPolicy: "legacy-read-only",
    cancelPolicy: "legacy-only",
    branchCut: "none-legacy",
    payload: "cpu-delta",
    payloadOwner: "legacy-vector-action",
    release: "legacy-compat",
    replay: "metadata-swap",
    undoRedoPath: "existing vector snapshots may retain immutable image asset metadata",
    spillable: false,
    selection: "none",
    faultBoundary: "structural-gpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "no new semantic image mutation is admitted; legacy snapshots remain replayable",
    verifiers: ["verify-raster-image.mjs", "verify-project-storage.mjs"],
  },
  {
    id: "raster-image-import",
    family: "semantic-scene",
    status: "current",
    owner: "engine-raster-image-runtime",
    currentMethods: ["importRasterImageFile"],
    actionKinds: ["raster-import"],
    batchKinds: [],
    lifecycle: "structural-transaction",
    commitPolicy: "post-structural-apply",
    cancelPolicy: "not-applicable",
    branchCut: "on-commit",
    payload: "cold-seed",
    payloadOwner: "history-action",
    release: "redo-compaction",
    replay: "structural-swap",
    undoRedoPath: "moveHistoryCursor -> applyRasterImportHistory",
    spillable: true,
    selection: "none",
    faultBoundary: "structural-gpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "destroy the imported seed/resources and restore scene selection/order",
    verifiers: ["verify-raster-image.mjs"],
  },
  {
    id: "vector-rasterize",
    family: "semantic-scene",
    status: "current",
    owner: "engine-vector-rasterize-runtime",
    currentMethods: ["rasterizeVectorTextNode", "rasterizeVectorSvgNode"],
    actionKinds: ["vector-rasterize"],
    batchKinds: [],
    lifecycle: "structural-transaction",
    commitPolicy: "post-structural-apply",
    cancelPolicy: "not-applicable",
    branchCut: "on-commit",
    payload: "cold-seed",
    payloadOwner: "history-action",
    release: "redo-compaction",
    replay: "structural-swap",
    undoRedoPath: "moveHistoryCursor -> applyVectorRasterizeHistory",
    spillable: true,
    selection: "none",
    faultBoundary: "structural-gpu",
    currentAtomicity: "verified",
    currentRisk: null,
    recovery: "destroy the raster seed or restore the semantic source and previous active raster",
    verifiers: ["verify-vector-text.mjs"],
  },
] as const satisfies readonly HistoryActionCharacterization[];
