import type { BrushEngine } from "./brush-engine.ts";

/**
 * Compile-time adapter for the engine-specific checkpoint/accounting runtime.
 * Adding a new engine dependency requires changing this explicit capability
 * list; generic History modules never receive the full BrushEngine type.
 */
export type EngineHistoryMaintenanceHost = Pick<
  BrushEngine,
  | "activeFillPreviewSession"
  | "activeRasterGaussianBlurSession"
  | "activeRasterLayerMetadataHistoryEdit"
  | "activeRasterLiquifySession"
  | "activeRasterMotionBlurSession"
  | "activeRasterNoiseSession"
  | "activeRasterTransformSession"
  | "activeStroke"
  | "activeVectorHistoryEdit"
  | "compactDiscardedHistoryIncrementally"
  | "customBrushAssets"
  | "device"
  | "deviceLostError"
  | "discardedLayerAddHistoryActions"
  | "discardedLayerDeleteHistoryActions"
  | "discardedLayerMergeHistoryActions"
  | "discardedRasterImportHistoryActions"
  | "discardedRasterTransformHistoryActions"
  | "discardedVectorRasterHistoryActions"
  | "effectsWorkbench"
  | "history"
  | "historyActions"
  | "historyBatches"
  | "historyBusy"
  | "historyCompactionPending"
  | "historyCursor"
  | "historyGpuStorage"
  | "historyLocalStorage"
  | "historyStateInconsistent"
  | "initialized"
  | "layerContentBounds"
  | "layerFormat"
  | "layerHasContent"
  | "layerStack"
  | "layerSwitchBusy"
  | "maybeInjectLayerColdStorageFault"
  | "publishHistoryState"
  | "publishStats"
  | "rasterBevelBusy"
  | "rasterBevelRenderer"
  | "rasterImageGpuResources"
  | "rasterInnerShadowBusy"
  | "rasterInnerShadowRenderer"
  | "rasterOuterShadowBusy"
  | "rasterOuterShadowRenderer"
  | "rasterStrokeBusy"
  | "rasterStrokeRenderer"
  | "requireLayerGpu"
  | "resumeHistoryStorageMaintenance"
  | "scheduleEffectsScratchShrink"
  | "selectionBusy"
  | "selectionHistoryClipBindGroups"
  | "selectionHistoryMasksByAction"
  | "selectionHistoryMasksByRevision"
  | "waitForGpuCapped"
  | "waitForIdle"
>;
