export const DESTRUCTIVE_MOTION_BLUR_CORE_BUILD =
  "destructive-motion-blur-core-v1-centered-power-of-two-exposures";

export const DESTRUCTIVE_MOTION_BLUR_DEFAULT_DISTANCE = 20;
export const DESTRUCTIVE_MOTION_BLUR_MAX_DISTANCE = 500;
export const DESTRUCTIVE_MOTION_BLUR_DISTANCE_STEP = 1;
export const DESTRUCTIVE_MOTION_BLUR_DEFAULT_ANGLE = 0;
export const DESTRUCTIVE_MOTION_BLUR_MIN_ANGLE = -180;
export const DESTRUCTIVE_MOTION_BLUR_MAX_ANGLE = 180;

export interface MotionBlurRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface MotionBlurKernel {
  /** Full length of the centered exposure line, in document pixels. */
  distance: number;
  /** UI angle in degrees. Positive values rotate counter-clockwise. */
  angle: number;
  /** Unit direction in document coordinates (whose Y axis points down). */
  directionX: number;
  directionY: number;
  /** Power-of-two exposure count generated by the logarithmic pass chain. */
  sampleCount: number;
  passCount: number;
  sampleSpacing: number;
  supportX: number;
  supportY: number;
  /** Per-pass symmetric shifts. Their Minkowski sum spans distance / 2. */
  shifts: readonly Readonly<{ x: number; y: number }>[];
}

function finite(value: unknown, fallback: number): number {
  const number = Number(value);
  return Number.isFinite(number) ? number : fallback;
}

function clamp(value: number, minimum: number, maximum: number): number {
  return Math.max(minimum, Math.min(maximum, value));
}

export function normalizeDestructiveMotionBlurDistance(value: unknown): number {
  return clamp(
    finite(value, DESTRUCTIVE_MOTION_BLUR_DEFAULT_DISTANCE),
    0,
    DESTRUCTIVE_MOTION_BLUR_MAX_DISTANCE,
  );
}

export function normalizeDestructiveMotionBlurAngle(value: unknown): number {
  return clamp(
    finite(value, DESTRUCTIVE_MOTION_BLUR_DEFAULT_ANGLE),
    DESTRUCTIVE_MOTION_BLUR_MIN_ANGLE,
    DESTRUCTIVE_MOTION_BLUR_MAX_ANGLE,
  );
}

function nextPowerOfTwo(value: number): number {
  let result = 1;
  while (result < value) result *= 2;
  return result;
}

export function destructiveMotionBlurKernel(
  distanceValue: unknown,
  angleValue: unknown,
): MotionBlurKernel {
  const distance = normalizeDestructiveMotionBlurDistance(distanceValue);
  const angle = normalizeDestructiveMotionBlurAngle(angleValue);
  const radians = angle * Math.PI / 180;
  const rawDirectionX = Math.cos(radians);
  const rawDirectionY = -Math.sin(radians);
  const directionX = Math.abs(rawDirectionX) < 1e-12 ? 0 : rawDirectionX;
  const directionY = Math.abs(rawDirectionY) < 1e-12 ? 0 : rawDirectionY;
  if (distance === 0) {
    return {
      distance,
      angle,
      directionX,
      directionY,
      sampleCount: 1,
      passCount: 0,
      sampleSpacing: 0,
      supportX: 0,
      supportY: 0,
      shifts: Object.freeze([]),
    };
  }

  // A power-of-two number of equally weighted exposures can be evaluated in
  // log2(N) passes: every pass averages two copies of the previous one at
  // symmetric, doubling offsets. Keeping spacing <= 1 px avoids visible gaps
  // while 500 px still needs only nine passes instead of 501 taps per pixel.
  const sampleCount = nextPowerOfTwo(Math.max(2, Math.ceil(distance) + 1));
  const passCount = Math.log2(sampleCount);
  const sampleSpacing = distance / (sampleCount - 1);
  const shifts = new Array<{ x: number; y: number }>(passCount);
  for (let pass = 0; pass < passCount; pass += 1) {
    const magnitude = sampleSpacing * 0.5 * (2 ** pass);
    shifts[pass] = {
      x: directionX * magnitude,
      y: directionY * magnitude,
    };
  }
  // Every stage uses bilinear reconstruction. Its discrete footprint grows by
  // ceil(abs(shift)) on each axis, so summing the stage footprints avoids
  // clipping the very faint outer pixels introduced by fractional shifts.
  const supportX = shifts.reduce(
    (total, shift) => total + Math.ceil(Math.abs(shift.x)),
    0,
  );
  const supportY = shifts.reduce(
    (total, shift) => total + Math.ceil(Math.abs(shift.y)),
    0,
  );
  return {
    distance,
    angle,
    directionX,
    directionY,
    sampleCount,
    passCount,
    sampleSpacing,
    supportX,
    supportY,
    shifts: Object.freeze(shifts.map((shift) => Object.freeze(shift))),
  };
}

export function normalizeMotionBlurRect(
  rect: MotionBlurRect | null | undefined,
  documentWidth: number,
  documentHeight: number,
): MotionBlurRect | null {
  if (!rect) return null;
  const x = clamp(Math.floor(finite(rect.x, 0)), 0, documentWidth);
  const y = clamp(Math.floor(finite(rect.y, 0)), 0, documentHeight);
  const right = clamp(
    Math.ceil(finite(rect.x, 0) + Math.max(0, finite(rect.width, 0))),
    0,
    documentWidth,
  );
  const bottom = clamp(
    Math.ceil(finite(rect.y, 0) + Math.max(0, finite(rect.height, 0))),
    0,
    documentHeight,
  );
  return right > x && bottom > y
    ? { x, y, width: right - x, height: bottom - y }
    : null;
}

export function destructiveMotionBlurBounds(
  contentBounds: MotionBlurRect | null | undefined,
  distance: unknown,
  angle: unknown,
  documentWidth: number,
  documentHeight: number,
): MotionBlurRect | null {
  const normalized = normalizeMotionBlurRect(
    contentBounds,
    documentWidth,
    documentHeight,
  );
  if (!normalized) return null;
  const kernel = destructiveMotionBlurKernel(distance, angle);
  return normalizeMotionBlurRect({
    x: normalized.x - kernel.supportX,
    y: normalized.y - kernel.supportY,
    width: normalized.width + kernel.supportX * 2,
    height: normalized.height + kernel.supportY * 2,
  }, documentWidth, documentHeight);
}

export function destructiveMotionBlurMaximumBounds(
  contentBounds: MotionBlurRect | null | undefined,
  documentWidth: number,
  documentHeight: number,
): MotionBlurRect | null {
  const normalized = normalizeMotionBlurRect(
    contentBounds,
    documentWidth,
    documentHeight,
  );
  if (!normalized) return null;
  const maximumPassCount = destructiveMotionBlurKernel(
    DESTRUCTIVE_MOTION_BLUR_MAX_DISTANCE,
    0,
  ).passCount;
  const maximumSupport = Math.ceil(DESTRUCTIVE_MOTION_BLUR_MAX_DISTANCE * 0.5)
    + maximumPassCount;
  return normalizeMotionBlurRect({
    x: normalized.x - maximumSupport,
    y: normalized.y - maximumSupport,
    width: normalized.width + maximumSupport * 2,
    height: normalized.height + maximumSupport * 2,
  }, documentWidth, documentHeight);
}

export function unionMotionBlurRects(
  left: MotionBlurRect | null | undefined,
  right: MotionBlurRect | null | undefined,
): MotionBlurRect | null {
  if (!left) return right ? { ...right } : null;
  if (!right) return { ...left };
  const x = Math.min(left.x, right.x);
  const y = Math.min(left.y, right.y);
  const rightEdge = Math.max(left.x + left.width, right.x + right.width);
  const bottom = Math.max(left.y + left.height, right.y + right.height);
  return { x, y, width: rightEdge - x, height: bottom - y };
}
