export {
  PROJECT_DOCUMENT_SCHEMA_VERSION,
  PROJECT_MANIFEST_MAGIC,
  PROJECT_STORAGE_DATABASE_NAME,
  PROJECT_STORAGE_DATABASE_VERSION,
  PROJECT_STORAGE_LEGACY_DOCUMENT_DIMENSION,
  PROJECT_STORAGE_MAX_CHUNK_BYTES,
  PROJECT_STORAGE_MAX_DOCUMENT_DIMENSION,
  PROJECT_STORAGE_MAX_LAYERS,
  PROJECT_STORAGE_MAX_THUMBNAIL_BYTES,
  PROJECT_STORAGE_MAX_TITLE_LENGTH,
  PROJECT_STORAGE_MIN_DOCUMENT_DIMENSION,
  PROJECT_STORAGE_QUOTA_RESERVE_BYTES,
  PROJECT_STORAGE_TILE_COUNT,
  PROJECT_STORAGE_TILE_GRID_SIZE,
  PROJECT_STORAGE_TILE_MASK_WORDS,
  ProjectStorageError,
  ProjectStorageValidationError,
} from "./project-storage-schema.ts";
export type {
  ProjectChunkWriteV1,
  ProjectDocumentDescriptorV1,
  ProjectLayerChunkDescriptorV1,
  ProjectLayerPixelsV1,
  ProjectLayerV1,
  ProjectLoadResultV1,
  ProjectManifestV1,
  ProjectMixedSceneStateV1,
  ProjectRectV1,
  ProjectSaveRequestV1,
  ProjectSnapshotV1,
  ProjectStorageBackend,
  ProjectStorageCapacity,
  ProjectStorageManagerLike,
  ProjectStorageOptions,
  ProjectStorageQuotaEstimate,
  ProjectStoredChunkV1,
  ProjectSummaryV1,
  ProjectViewStateV1,
} from "./project-storage-schema.ts";
export {
  normalizeProjectTitle,
  validateLoadedProject,
  validateProjectManifest,
  validateProjectSaveRequest,
} from "./project-storage-codec.ts";
export {
  checkProjectStorageCapacity,
  estimateProjectSaveBytes,
  estimateProjectStorageQuota,
  requestPersistentProjectStorage,
} from "./project-storage-quota.ts";
export {
  createProjectStorage,
  ProjectStorage,
} from "./project-storage-repository.ts";
